# Site settings
title: Benjamin Nicholes
tag_text: Benjamin Nicholes
description: DevOps Engineer and on the side I like to have fun.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
